# Generated by Django 4.1.6 on 2023-04-29 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_app', '0005_usercreditcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField()),
                ('credit_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='levelup_app.usercreditcard')),
            ],
        ),
    ]
