# Generated by Django 4.1.6 on 2023-05-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelup_app', '0008_product_in_sale_product_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardmoney',
            name='money',
            field=models.FloatField(default=0),
        ),
    ]
